# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Amir\Desktop\SCSHub\scshub\view\ui\pix_hasher_fil_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class PixFileHasherUi(object):
    def setupUi(self, PixFileHasher):
        PixFileHasher.setObjectName("PixFileHasher")
        PixFileHasher.resize(987, 759)
        self.main_lyt = QtWidgets.QVBoxLayout(PixFileHasher)
        self.main_lyt.setContentsMargins(0, 0, 0, 0)
        self.main_lyt.setSpacing(30)
        self.main_lyt.setObjectName("main_lyt")
        self.main_card = SimpleCardWidget(PixFileHasher)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_card.sizePolicy().hasHeightForWidth())
        self.main_card.setSizePolicy(sizePolicy)
        self.main_card.setObjectName("main_card")
        self.main_card_lyt = QtWidgets.QVBoxLayout(self.main_card)
        self.main_card_lyt.setObjectName("main_card_lyt")
        self.file_hasher_lbl = StrongBodyLabel(self.main_card)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_hasher_lbl.sizePolicy().hasHeightForWidth())
        self.file_hasher_lbl.setSizePolicy(sizePolicy)
        self.file_hasher_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.file_hasher_lbl.setObjectName("file_hasher_lbl")
        self.main_card_lyt.addWidget(self.file_hasher_lbl)
        self.top_card = SimpleCardWidget(self.main_card)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_card.sizePolicy().hasHeightForWidth())
        self.top_card.setSizePolicy(sizePolicy)
        self.top_card.setMinimumSize(QtCore.QSize(0, 60))
        self.top_card.setMaximumSize(QtCore.QSize(16777215, 60))
        self.top_card.setObjectName("top_card")
        self.top_card_lyt = QtWidgets.QHBoxLayout(self.top_card)
        self.top_card_lyt.setObjectName("top_card_lyt")
        self.input_btn = PushButton(self.top_card)
        self.input_btn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_btn.sizePolicy().hasHeightForWidth())
        self.input_btn.setSizePolicy(sizePolicy)
        self.input_btn.setMinimumSize(QtCore.QSize(110, 0))
        self.input_btn.setObjectName("input_btn")
        self.top_card_lyt.addWidget(self.input_btn)
        self.hash_line = LineEdit(self.top_card)
        self.hash_line.setText("")
        self.hash_line.setMaxLength(1000)
        self.hash_line.setReadOnly(True)
        self.hash_line.setObjectName("hash_line")
        self.top_card_lyt.addWidget(self.hash_line)
        self.hex_line = LineEdit(self.top_card)
        self.hex_line.setText("")
        self.hex_line.setMaxLength(1000)
        self.hex_line.setReadOnly(True)
        self.hex_line.setObjectName("hex_line")
        self.top_card_lyt.addWidget(self.hex_line)
        self.main_card_lyt.addWidget(self.top_card)
        self.main_lyt.addWidget(self.main_card)

        self.retranslateUi(PixFileHasher)
        QtCore.QMetaObject.connectSlotsByName(PixFileHasher)

    def retranslateUi(self, PixFileHasher):
        _translate = QtCore.QCoreApplication.translate
        PixFileHasher.setWindowTitle(_translate("PixFileHasher", "PixFileHasher"))
        self.file_hasher_lbl.setText(_translate("PixFileHasher", "File Hasher"))
        self.input_btn.setText(_translate("PixFileHasher", "Input"))
        self.hash_line.setPlaceholderText(_translate("PixFileHasher", "Hash"))
        self.hex_line.setPlaceholderText(_translate("PixFileHasher", "Hex"))
from qfluentwidgets import LineEdit, PushButton, SimpleCardWidget, StrongBodyLabel
