# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Amir\Desktop\SCSHub\scshub\view\ui\pix_hasher_str_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class PixStringHasherUi(object):
    def setupUi(self, PixStringHasher):
        PixStringHasher.setObjectName("PixStringHasher")
        PixStringHasher.resize(987, 759)
        self.main_lyt = QtWidgets.QVBoxLayout(PixStringHasher)
        self.main_lyt.setContentsMargins(0, 0, 0, 0)
        self.main_lyt.setSpacing(30)
        self.main_lyt.setObjectName("main_lyt")
        self.mainCrd = SimpleCardWidget(PixStringHasher)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainCrd.sizePolicy().hasHeightForWidth())
        self.mainCrd.setSizePolicy(sizePolicy)
        self.mainCrd.setObjectName("mainCrd")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.mainCrd)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.string_hasher_lbl = StrongBodyLabel(self.mainCrd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.string_hasher_lbl.sizePolicy().hasHeightForWidth())
        self.string_hasher_lbl.setSizePolicy(sizePolicy)
        self.string_hasher_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.string_hasher_lbl.setObjectName("string_hasher_lbl")
        self.verticalLayout_3.addWidget(self.string_hasher_lbl)
        self.top_card = SimpleCardWidget(self.mainCrd)
        self.top_card.setObjectName("top_card")
        self.top_card_lyt = QtWidgets.QVBoxLayout(self.top_card)
        self.top_card_lyt.setContentsMargins(-1, 14, -1, 14)
        self.top_card_lyt.setObjectName("top_card_lyt")
        self.input_line = LineEdit(self.top_card)
        self.input_line.setEnabled(False)
        self.input_line.setText("")
        self.input_line.setMaxLength(1000)
        self.input_line.setClearButtonEnabled(True)
        self.input_line.setObjectName("input_line")
        self.top_card_lyt.addWidget(self.input_line)
        self.hash_lyt = QtWidgets.QHBoxLayout()
        self.hash_lyt.setObjectName("hash_lyt")
        self.hash_line = LineEdit(self.top_card)
        self.hash_line.setMaxLength(1000)
        self.hash_line.setReadOnly(True)
        self.hash_line.setObjectName("hash_line")
        self.hash_lyt.addWidget(self.hash_line)
        self.hex_line = LineEdit(self.top_card)
        self.hex_line.setMaxLength(1000)
        self.hex_line.setReadOnly(True)
        self.hex_line.setObjectName("hex_line")
        self.hash_lyt.addWidget(self.hex_line)
        self.top_card_lyt.addLayout(self.hash_lyt)
        self.verticalLayout_3.addWidget(self.top_card)
        self.main_lyt.addWidget(self.mainCrd)

        self.retranslateUi(PixStringHasher)
        QtCore.QMetaObject.connectSlotsByName(PixStringHasher)

    def retranslateUi(self, PixStringHasher):
        _translate = QtCore.QCoreApplication.translate
        PixStringHasher.setWindowTitle(_translate("PixStringHasher", "PixStringHasher"))
        self.string_hasher_lbl.setText(_translate("PixStringHasher", "String Hasher"))
        self.input_line.setPlaceholderText(_translate("PixStringHasher", "Input string"))
        self.hash_line.setPlaceholderText(_translate("PixStringHasher", "Hash"))
        self.hex_line.setPlaceholderText(_translate("PixStringHasher", "Hex"))
from qfluentwidgets import LineEdit, SimpleCardWidget, StrongBodyLabel
